### ISSUE TITLE
Notify me unintuitive

### ISSUE THREAD

**Issue by ShwangShwing** [ShwangShwing/sofia-swing-dance-festival-android#25]
The notify me feature is not as intuitive as it was hoped to be. Some people were discovered to click on the event, and then click on the notify me! text, which removes the notificaiton. Think of a less confusing way to accomplish the task.

**Comment by ShwangShwing** [comment]
Maybe a message that says "you will be notified", "you have removed your notification" will be helpful also.

**Comment by ivorcho** [comment]
Clicking on events will now open new activity showing details about the event. And we will have a trompet(grey/yellow) icon for notification subscribing. Use notification provider for subscribe/unsubscribe message.

**Comment by ShwangShwing** [comment]
Done
