### ISSUE TITLE
Back button should not exit immediately

### ISSUE THREAD

**Issue by ShwangShwing** [ShwangShwing/sofia-swing-dance-festival-android#26]
The back button should display message like "press again to exit" and require second press to exit (this was confirmed to confuse many users). Ideally the back button should bring back the previous menu item.

**Comment by ivorcho** [comment]
back button will go back to previuos screen

**Comment by ShwangShwing** [comment]
Back button will not go to the previous screen as I prefer not to implement it that way (he, he, the advantage of doing stuff for free is that you can implement things as you like them, not as the masses like them). Now the user needs to press back twice to exit the application.
